engines:
  eslint:
    enabled: true
    channel: "eslint-5"
    checks:
      ember/no-observers:
        enabled: false
      ember/no-string-prototype-extensions:
        enabled: false
      ember/no-controller-access-in-routes:
        enabled: false
      ember/no-classic-classes:
        enabled: false
      ember/no-computed-properties-in-native-classes:
        enabled: false
      ember/require-tagless-components:
        enabled: false
      ember/no-assignment-of-untracked-properties-used-in-tracking-contexts:
        enabled: false
      ember/no-side-effects:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
ratings:
  paths:
    - "app/**/*"
exclude_paths:
  - ".eslintrc.js"
  - ".template-lintrc.js"
  - "config/tailwindcss-config.js"
  - "release/**/*"
  - "scripts/**/*"
  - "tests/**/*"
