engines:
  eslint:
    enabled: true
    channel: "eslint-5"
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
ratings:
  paths:
    - "app/**/*"
exclude_paths:
  - "tests/**/*"
  - ".eslintrc.js"
  - ".template-lintrc.js"
