version: "2"
checks:
  similar-code:
    config:
      threshold: 60
  identical-code:
    config:
      threshold: 60
  method-lines:
    enabled: true
    config:
      threshold: 30
# plugins:
#   fixme:
#     enabled: true
#     config:
#       strings:
#       - TODO
#       - FIXME
exclude_patterns:
- ".eslintrc.js"
- ".template-lintrc.js"
- "config/tailwindcss-config.js"
- "release/"
- "scripts/"
- "tests/"
- "node_modules/"
