---
dist: trusty
language: node_js
node_js:
  - "6"

sudo: false

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - npm install

script:
  - npm test
