---
dist: trusty
language: node_js
node_js:
  - "6"

sudo: required

services:
  - redis-server

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - npm install
  - npm install sockethub

before_script:
  - ./node_modules/sockethub/bin/sockethub 2> /dev/null &

script:
  - npm run lint:js
  - npm test
