---
dist: trusty
language: node_js
node_js:
  - "6"

sudo: required

services:
  - redis-server

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - $HOME/sockethub

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - mkdir -p $HOME/sockethub
  - cd $HOME/sockethub
  - npm install sockethub
  - cd node_modules/sockethub
  - npm install
  - cd $TRAVIS_BUILD_DIR
  - npm install

before_script:
  - $HOME/sockethub/node_modules/sockethub/bin/sockethub 2> /dev/null &

script:
  - npm run lint:js
  - npm test
