dist: xenial
language: node_js
node_js:
  - 16

notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

services:
  - redis-server

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

install:
  - cd $HOME
  - git clone https://github.com/sockethub/sockethub.git
  - cd sockethub
  - git checkout 8161f89
  - yarn run deps
  - yarn run build
  - cd $TRAVIS_BUILD_DIR
  - cp sockethub.config.json $HOME/sockethub/packages/sockethub/
  - npm ci

before_script:
  - cd $HOME/sockethub
  - find . -name sockethub-client.js
  - yarn start 2> /dev/null &

branches:
  only:
    - master

script:
  - cd $TRAVIS_BUILD_DIR
  - npm test
