dist: xenial
language: node_js
node_js:
  - 14

notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

services:
  - redis-server

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

install:
  - cd $HOME
  - git clone https://github.com/sockethub/sockethub.git
  - cd sockethub
  - git checkout sockethub@5.0.0-alpha.3
  - yarn run deps
  - yarn run build
  - cd $TRAVIS_BUILD_DIR
  - npm ci

before_script:
  - cd $HOME/sockethub
  - yarn start 2> /dev/null &

branches:
  only:
    - master

script:
  - cd $TRAVIS_BUILD_DIR
  - npm test
