name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Lint JavaScript
        run: npm run lint:js
      - name: Lint Templates
        run: npm run lint:hbs
      - name: Lint CSS
        run: npm run lint:css
      - name: Check Formatting
        run: npm run lint:format

  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:ember

  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build Production
        run: npm run build
